[package]
name = "linear-quadtree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
embedded-graphics = "0.7.1"

[dev-dependencies]
embedded-graphics-simulator = "0.3"
