[package]
edition = "2018"
name = "linear-quadtree"
version = "0.1.2"

[[bin]]
name = "linear-quadtree"

[features]
default = ["enc", "dec"]
enc = []
dec = []

[dependencies]
argh = "0.1.5"
bitvec = "0.22.3"
embedded-graphics = "0.7.1"

[dev-dependencies]
embedded-graphics-simulator = { version = "0.3", default-features = false }
