[package]
edition = "2018"
name = "linear-quadtree"
version = "0.1.1"
[[bin]]
name = "linear-quadtree"

[dependencies]
argh = "*"
bitvec = "0.22.3"
embedded-graphics = "0.7.1"

[dev-dependencies]
embedded-graphics-simulator = { version = "0.3", default-features = false }
